### ISSUE TITLE
Developer mode - correct areas do not show

### ISSUE THREAD

**Issue by hbaileylxd** [chris-steele/adapt-ppq#3]
I have selected true for developer mode, but do not see the clickable areas when previewing.

**Comment by chris-steele** [comment]
@hmaffin when you have time would you mind veriyfing this fix works for you?

**Comment by hbaileylxd** [comment]
Sure will! Ahhh not version upped. Yes I'm using the AT!

**Comment by hbaileylxd** [comment]
I now see a nice big red box over my image with developer mode turned on :)

**Comment by chris-steele** [comment]
Awesome!
